VCTK_DATASET_SAMPLING_RATE = 48000
RESAMPLING_FACTOR = 4
DOWNSAMPLED_RATE = int(VCTK_DATASET_SAMPLING_RATE / RESAMPLING_FACTOR)
OVERLAP = 128
SAMPLE_DIMENSION = 256
NUMBER_OF_EPOCHS = 100
BATCH_SIZE = 16
